export default {
    'SERVICES_WEBSITE_QUOTE':'Du site web vitrine pour présenter votre activité, au site web complexe qui donnera la vie à vos idées les plus insolites !',
    'SERVICES_E_COMMERCE_QUOTE':'Du site web vitrine pour présenter votre activité, au site web complexe qui donnera la vie à vos idées les plus insolites !',
    'SERVICES_MARKETING_DIGITAL_QUOTE':'Du site web vitrine pour présenter votre activité, au site web complexe qui donnera la vie à vos idées les plus insolites !',
    'SERVICES_SEO_QUOTE':'Du site web vitrine pour présenter votre activité, au site web complexe qui donnera la vie à vos idées les plus insolites !',
    'SERVICES_TRAININGS_QUOTE':'Du site web vitrine pour présenter votre activité, au site web complexe qui donnera la vie à vos idées les plus insolites !',
    'WEBSITE_IMAGE_TEXT':'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer suscipit venenatis congue. Maecenas aliquam elit ut scelerisque imperdiet. Vestibulum at bibendum sapien. Proin ac ante eget nisi volutpat auctor. Nullam aliquam nisl vel lectus finibus interdum. Cras sapien urna, sollicitudin quis erat at, consectetur viverra nunc. Cras dui quam, cursus non mi sed, sagittis facilisis nisi. Nullam finibus porttitor nibh. Sed ex nisi, venenatis et semper a, mollis in dolor. Fusce sit amet sapien facilisis, viverra ante nec, finibus libero. Curabitur at malesuada lectus, id scelerisque lorem.',
    'WEBSITE_SECOND_TITLE':'Fusce sit amet fermentum velit.',
    'WEBSITE_SECOND_TEXT':'Pellentesque nisi ex, rutrum sed ex sit amet, porta vulputate nisi. Nunc ut nibh dui. Nulla dignissim bibendum laoreet. Integer ullamcorper imperdiet enim, eu ultricies nibh accumsan vel. Ut nisl lorem, dictum eget dui ac, suscipit rhoncus libero. Vestibulum vitae aliquet ante, eget vulputate massa. Donec quis purus eget ligula laoreet lobortis. Nunc sed tristique elit, sodales bibendum turpis. Proin ut tempor leo. In interdum, lacus id cursus volutpat, odio nisi vulputate massa, at tristique purus quam in urna. Duis id risus consectetur, ullamcorper sapien nec, semper nisl. Nunc quis pulvinar ante, vitae scelerisque purus. Nullam varius porttitor porta. Aenean tempor consequat orci. Donec venenatis lectus ut quam auctor pretium.',
    'WEBSITE_THIRD_TEXT':'Nunc quam diam, pellentesque non ligula nec, aliquet suscipit arcu. Nam sed egestas felis. Integer placerat leo in lacinia venenatis. Praesent lorem sem, volutpat eget odio non, scelerisque ullamcorper velit. Nunc non mauris placerat, volutpat neque eu, ullamcorper est. Sed rhoncus efficitur luctus. Aenean congue ipsum a enim vulputate, quis maximus nibh porta. Phasellus lacinia turpis non velit ultrices, ac vestibulum nibh hendrerit. Etiam a massa molestie, fermentum odio id, tristique ante. Ut elementum ante quis erat fermentum, vel semper mi pulvinar. Donec feugiat sagittis arcu vitae sagittis.',
    'E_COMMERCE_IMAGE_TEXT':'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer suscipit venenatis congue. Maecenas aliquam elit ut scelerisque imperdiet. Vestibulum at bibendum sapien. Proin ac ante eget nisi volutpat auctor. Nullam aliquam nisl vel lectus finibus interdum. Cras sapien urna, sollicitudin quis erat at, consectetur viverra nunc. Cras dui quam, cursus non mi sed, sagittis facilisis nisi. Nullam finibus porttitor nibh. Sed ex nisi, venenatis et semper a, mollis in dolor. Fusce sit amet sapien facilisis, viverra ante nec, finibus libero. Curabitur at malesuada lectus, id scelerisque lorem.',
    'E_COMMERCE_SECOND_TITLE':'Fusce sit amet fermentum velit.',
    'E_COMMERCE_SECOND_TEXT':'Pellentesque nisi ex, rutrum sed ex sit amet, porta vulputate nisi. Nunc ut nibh dui. Nulla dignissim bibendum laoreet. Integer ullamcorper imperdiet enim, eu ultricies nibh accumsan vel. Ut nisl lorem, dictum eget dui ac, suscipit rhoncus libero. Vestibulum vitae aliquet ante, eget vulputate massa. Donec quis purus eget ligula laoreet lobortis. Nunc sed tristique elit, sodales bibendum turpis. Proin ut tempor leo. In interdum, lacus id cursus volutpat, odio nisi vulputate massa, at tristique purus quam in urna. Duis id risus consectetur, ullamcorper sapien nec, semper nisl. Nunc quis pulvinar ante, vitae scelerisque purus. Nullam varius porttitor porta. Aenean tempor consequat orci. Donec venenatis lectus ut quam auctor pretium.',
    'E_COMMERCE_THIRD_TEXT':'Nunc quam diam, pellentesque non ligula nec, aliquet suscipit arcu. Nam sed egestas felis. Integer placerat leo in lacinia venenatis. Praesent lorem sem, volutpat eget odio non, scelerisque ullamcorper velit. Nunc non mauris placerat, volutpat neque eu, ullamcorper est. Sed rhoncus efficitur luctus. Aenean congue ipsum a enim vulputate, quis maximus nibh porta. Phasellus lacinia turpis non velit ultrices, ac vestibulum nibh hendrerit. Etiam a massa molestie, fermentum odio id, tristique ante. Ut elementum ante quis erat fermentum, vel semper mi pulvinar. Donec feugiat sagittis arcu vitae sagittis.'
}