export default {
    'TEXT_HOME_AGENCE_MISSION':'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a velit nunc. Donec diam metus, porta sed tincidunt ut, pellentesque vel eros. Duis suscipit venenatis convallis. Aenean id iaculis lectus. Vivamus tincidunt ante vel purus congue, viverra cursus risus imperdiet.',
    'TEXT_HOME_AGENCE_VISION':'Aenean pellentesque suscipit mi non elementum. Suspendisse cursus nulla quis auctor consequat. Fusce eu leo enim. Donec quis sodales orci, at condimentum erat. Duis vitae odio dignissim, aliquet elit vitae, imperdiet nibh. ',
    'TEXT_HOME_AGENCE_PROMISE':'Curabitur laoreet, ante vel pretium ultrices, nulla magna fringilla lacus, dictum elementum est leo nec tellus. Vestibulum eu tortor ut enim hendrerit blandit id a urna. Sed venenatis in urna eget egestas. Sed pulvinar mi nunc, eu convallis sem pharetra facilisis.',
    'TEXT_HOME_UPPER_BLOCK_CONTACT':'Aenean pellentesque suscipit mi non elementum. Suspendisse cursus nulla quis auctor consequat. Fusce eu leo enim. Donec quis sodales orci, at condimentum erat. Duis vitae odio dignissim, aliquet elit vitae, imperdiet nibh. ',
    'TEXT_HOME_UPPER_BLOCK_LOGO':'Curabitur laoreet, ante vel pretium ultrices, nulla magna fringilla lacus, dictum elementum est leo nec tellus. Vestibulum eu tortor ut enim hendrerit blandit id a urna. Sed venenatis in urna eget egestas. Sed pulvinar mi nunc, eu convallis sem pharetra facilisis.',
    'TEXT_SERVICES_PRESENTATION_WEBSITE':'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a velit nunc. Donec diam metus, porta sed tincidunt ut, pellentesque vel eros. Duis suscipit venenatis convallis. Aenean id iaculis lectus. Vivamus tincidunt ante vel purus congue, viverra cursus risus imperdiet.',
    'TEXT_SERVICES_PRESENTATION_E_COMMERCE':'Aenean pellentesque suscipit mi non elementum. Suspendisse cursus nulla quis auctor consequat. Fusce eu leo enim. Donec quis sodales orci, at condimentum erat. Duis vitae odio dignissim, aliquet elit vitae, imperdiet nibh. ',
    'TEXT_SERVICES_PRESENTATION_MARKETING_DIGITAL':'Curabitur laoreet, ante vel pretium ultrices, nulla magna fringilla lacus, dictum elementum est leo nec tellus. Vestibulum eu tortor ut enim hendrerit blandit id a urna. Sed venenatis in urna eget egestas. Sed pulvinar mi nunc, eu convallis sem pharetra facilisis.',
    'TEXT_SERVICES_PRESENTATION_SEO':'Aenean pellentesque suscipit mi non elementum. Suspendisse cursus nulla quis auctor consequat. Fusce eu leo enim. Donec quis sodales orci, at condimentum erat. Duis vitae odio dignissim, aliquet elit vitae, imperdiet nibh. ',
    'TEXT_SERVICES_PRESENTATION_TRAININGS':'Curabitur laoreet, ante vel pretium ultrices, nulla magna fringilla lacus, dictum elementum est leo nec tellus. Vestibulum eu tortor ut enim hendrerit blandit id a urna. Sed venenatis in urna eget egestas. Sed pulvinar mi nunc, eu convallis sem pharetra facilisis.'
}